const data = [
  {
    id: 1,
    title: "A Great Apartement Next to the Beach!",
    bedRooms: 2,
    bathRooms: 1,
    price: 1000,
    address: "123 Beach Lane",
    latitude: 25.7617,
    longitude: -80.1811,
    img: "./realEstateImage/ronnie-george-ZcQJeOvJgBQ-unsplash.jpg",
  },
  {
    id: 2,
    title: "Cozy Studio in Bustling Downtown",
    bedRooms: 1,
    bathRooms: 1,
    price: 800,
    address: "456 Main Street",
    latitude: 41.8885,
    longitude: -87.6231,
    img: "images/downtown_studio.jpg",
  },
  {
    id: 3,
    title: "Spacious Family Home with Pool",
    bedRooms: 4,
    bathRooms: 2.5,
    price: 2500,
    address: "789 Evergreen Drive",
    latitude: 34.0522,
    longitude: -118.2437,
    img: "images/family_home.jpg",
  },
  {
    id: 4,
    title: "Modern Loft with City Views",
    bedRooms: 1,
    bathRooms: 1,
    price: 1200,
    address: "01 High Street",
    latitude: 37.7749,
    longitude: -122.4194,
    img: "images/city_loft.jpg",
  },
  {
    id: 5,
    title: "Charming Cottage in Quiet Neighborhood",
    bedRooms: 2,
    bathRooms: 1,
    price: 900,
    address: "Maple Street", // No number provided
    latitude: 42.3601,
    longitude: -71.0589,
    img: "images/quiet_cottage.jpg",
  },
  {
    id: 6,
    title: "Luxury Penthouse with Rooftop Terrace",
    bedRooms: 3,
    bathRooms: 3,
    price: 5000,
    address: "100 Park Avenue",
    latitude: 40.7128,
    longitude: -74.006,
    img: "images/penthouse.jpg",
  },
  {
    id: 7,
    title: "Historic Townhouse with Private Garden",
    bedRooms: 3,
    bathRooms: 2,
    price: 1800,
    address: "567 Elm Street",
    latitude: 39.9526,
    longitude: -75.1652,
    img: "images/townhouse.jpg",
  },
  {
    id: 8,
    title: "Studio Apartment in Student District",
    bedRooms: 1,
    bathRooms: 1,
    price: 600,
    address: "University Avenue", // No number provided
    latitude: 40.4406,
    longitude: -80.0002,
    img: "images/student_studio.jpg",
  },
  {
    id: 9,
    title: "Waterfront Property with Boat Dock",
    bedRooms: 3,
    bathRooms: 2,
    price: 3000,
    address: "11 Waterside Lane",
    latitude: 28.5383,
    longitude: -81.3792,
    img: "images/waterfront.jpg",
  },
  {
    id: 10,
    title: "Cozy Cabin in the Mountains",
    bedRooms: 2,
    bathRooms: 1,
    price: 1500,
    address: "12 Pine Ridge Road",
    latitude: 40.1433,
    longitude: -105.5478,
    img: "images/mountain_cabin",
  },
];

export default data;
